# pgboard.py
# This module provides a Pygame-specific wrapper around the python-chess Board object
# for drawing and interacting with a chessboard in a Pygame window.

import pygame
import chess
import chess.svg # Used to generate SVG images of the board and pieces
import io         # Used to read SVG data from strings
from xml.dom import minidom

DEFAULT_PIECE_VIEWBOX = None
DEFAULT_BOARD_VIEWBOX = None
DEFAULT_BOARD_BORDERLESS_VIEWBOX = None

def _get_svg_viewbox( svg_str ):
    e = minidom.parseString( svg_str ).documentElement
    return [ int(x) for x in e.getAttribute("viewBox").split() ]

def _set_default_viewboxes():
    global DEFAULT_PIECE_VIEWBOX
    global DEFAULT_BOARD_VIEWBOX
    global DEFAULT_BOARD_BORDERLESS_VIEWBOX

    DEFAULT_PIECE_VIEWBOX = _get_svg_viewbox( str( chess.svg.piece( chess.Piece.from_symbol("Q") ) ) )
    DEFAULT_BOARD_VIEWBOX = _get_svg_viewbox( str( chess.svg.board( size=400 ) ) )
    DEFAULT_BOARD_BORDERLESS_VIEWBOX = _get_svg_viewbox( str( chess.svg.board(borders=False) ) )
    
def _prescale_svg(svg_str, size):
    e = minidom.parseString( svg_str ).documentElement
    vb_size = int( e.getAttribute("viewBox").split()[-1] )
    scale = size / vb_size
    e.setAttribute( "transform", f"scale({scale})" )
    e.setAttribute( "viewBox", f"0 0 {size} {size}" )
    e.setAttribute( "width", f"{size}" )
    e.setAttribute( "height", f"{size}" )
    return e.toprettyxml()

def _svg2image(svg,size=None):
    """
    Helper function to convert an SVG string generated by python-chess.svg
    into a Pygame Surface object.

    Args:
        svg (str): The SVG content as a string.

    Returns:
        pygame.Surface: The loaded image as a Pygame Surface.
    """
    # Load the SVG string into a file-like object (BytesIO).
    # Encode the string to bytes first, as image.load expects bytes.
    # pygame.image.load can read from file-like objects.
    svg_str = str(svg)
    if size:
        svg_str = _prescale_svg(svg_str, size)
    io_obj = io.BytesIO( svg_str.encode('utf-8') )
    return pygame.image.load( io_obj )

def _make_symbol(letter, size):
    """
    Helper function to create a Pygame Surface for a single chess piece
    of a specified size.

    Args:
        letter (str): The standard algebraic notation symbol for the piece
                      ('p', 'n', 'b', 'r', 'q', 'k' or their uppercase for White).
        size (int): The desired size in pixels for the piece image.

    Returns:
        pygame.Surface: The Pygame Surface representing the piece.
    """
    # Get the chess.Piece object from the symbol.
    piece = chess.Piece.from_symbol(letter)
    # Generate the SVG string for the piece using python-chess.svg.piece().
    # The size parameter scales the SVG output.
    svg = chess.svg.piece( piece, size )
    # Convert the SVG string to a Pygame Surface using the helper function.
    return _svg2image( svg, size )

# --- Custom Point Class ---
# A simple class to represent 2D points (x, y) with basic vector operations.
# This is used internally for calculating positions on the board grid.
class Pt:
    """
    A simple 2D point class with vector operations.
    Used for handling coordinates and sizes in the board rendering.
    """
    def __init__(self, x=None, y=None):
        self.x = x
        self.y = y

    # Define standard arithmetic operations for Pt objects
    def __add__(self, other):
        # Adds another Pt or scalar (scalar not directly used in provided code but good practice)
        if isinstance(other,Pt):
            return Pt(self.x + other.x, self.y + other.y)
        if isinstance(other,int) or isinstance(other,float):
            return Pt(self.x + other, self.y + other)
        raise TypeError(f"unsupported operand type(s) for +: 'Pt' and '{type(other)}'")

    def __sub__(self, other):
        # Subtracts another Pt
        return Pt(self.x - other.x, self.y - other.y)

    def __mul__(self, other):
        # Multiplies by another Pt (element-wise) or a scalar
        if isinstance(other,Pt):
            return Pt( self.x * other.x, self.y * other.y )
        if isinstance(other,int) or isinstance(other,float):
            return Pt( self.x * other, self.y * other )
        raise TypeError(f"unsupported operand type(s) for *: 'Pt' and '{type(other)}'")

    def __rmul__(self, fac):
        # Allows scalar multiplication from the left (e.g., 2 * Pt(1,1))
        return ( self * fac )

    def __floordiv__(self, denom):
        # Floor division by another Pt (element-wise) or a scalar
        try:
            return Pt(self.x // denom.x, self.y // denom.y)
        except AttributeError:
            return Pt(self.x // denom, self.y // denom)

    # Allow iterating over the point's coordinates (e.g., `tuple(pt)` or `x, y = pt`)
    def __iter__(self):
        yield self.x
        yield self.y

    def __str__(self):
        return f"Pt(x={self.x}, y={self.y})"

# --- Board Class ---
class Board:
    """
    Manages the visual representation and interaction for a chess board
    using Pygame, wrapping a python-chess.Board object.
    """
    def __init__(self, piece_size=45):
        """
        Initializes the Pygame board renderer.

        Args:
            piece_size (int): The desired size (width/height) of each piece image in pixels.
                              This scales the entire board rendering.
        """
        # Initialize the underlying python-chess Board object.
        self.board = chess.Board()
        self.piece_size = piece_size
        self.board_origin = Pt(0, 0)
        self._symbol_size = Pt(piece_size,piece_size)

        # --- Calculate Board Dimensions and Load Assets ---
        if not DEFAULT_PIECE_VIEWBOX:
            _set_default_viewboxes()
        default_piece_size = 45
        default_board_size = 375
        default_border_thickness = 15

        # Calculate the desired border size based on the requested `piece_size`.
        x = (piece_size * default_border_thickness) // default_piece_size
        self._border = Pt(x,x)
        print(self._border)

        # Load Pygame Surface images for all chess pieces.
        # Store them in a dictionary keyed by their symbol ('p', 'N', 'B', etc.).
        self._symbol = {}
        for letter in 'kqrbnp':
            self._symbol[letter] = _make_symbol(letter, piece_size) # Black pieces
            self._symbol[letter.upper()] = _make_symbol(letter.upper(), piece_size) # White pieces

        # Load the empty board background image.
        # We calculate the required SVG size based on 8 squares of _symbol_size
        # plus the calculated border size on both sides.
        board_svg_size = ( 2 * self._border ) + ( 8 * self._symbol_size.x ) # Assuming square board, use x dimension
        self._empty_board = _svg2image( str( chess.svg.board(size=400) ), size = board_svg_size.x ) # Generate SVG and convert
        print(self._empty_board.get_size())
        
        # Create a transparent yellow surface for highlighting squares.
        # The size matches the size of a single piece/square (_symbol_size).
        self._highlight = pygame.Surface(tuple(self._symbol_size))
        self._highlight.fill(pygame.Color(255, 255, 0)) # Yellow color
        self._highlight.set_alpha(65) # Semi-transparent (0 is fully transparent, 255 is opaque)

        # List to store the indices of squares that should be highlighted.
        # These are chess.square constants (0 to 63).
        self._highlighted = []

        # Flag to track if the board is currently flipped (White at bottom vs. Black at bottom).
        self.flipped = False
        # Initial flip if needed (the board is drawn with White at bottom by default).
        # The _empty_board is loaded assuming not flipped. If `self.flipped` is True initially,
        # it should be flipped here or handled during the first draw. The current code
        # loads it unflipped and relies on `flip()` to regenerate the SVG if needed later.
        # A more robust approach might be to load based on initial `flipped` state.
        # For this code's flow (flipped is initially False), loading unflipped is correct.


    def __getattr__(self, attr):
        """
        Allows accessing attributes and methods of the underlying python-chess Board
        object directly through the pgboard.Board instance.
        e.g., `board.legal_moves` will call `board.board.legal_moves`.
        """
        return getattr(self.board, attr)

    def flip(self):
        """
        Toggles the board orientation (flips the view).
        Regenerates the empty board background SVG with the new orientation.
        """
        self.flipped = not self.flipped
        # Regenerate the empty board SVG with the flipped flag set.
        # Use the same size as the current _empty_board to maintain consistency.
        self._empty_board = _svg2image(chess.svg.board(flipped=self.flipped),size=self._empty_board.get_width() )

    def draw(self, screen):
        """
        Draws the current state of the chessboard onto the given Pygame screen surface.

        Args:
            screen (pygame.Surface): The surface to draw the board onto.
        """
        # 1. Draw the empty board background.
        screen.blit( self._empty_board, tuple( self.board_origin) )

        # 2. Draw square highlights (e.g., for last move, selected square).
        # Iterate through the list of squares to be highlighted.
        for square in self._highlighted:
            # Determine the file (column) and rank (row) of the square (0-7).
            file_index = chess.square_file(square)
            rank_index = chess.square_rank(square)
            # Calculate the position (in grid coordinates, 0-7) on the screen grid.
            # If flipped, file 0 is on the right (7), rank 0 is at the top (7).
            # If not flipped, file 0 is on the left (0), rank 0 is at the bottom (7).
            square_grid_pos = Pt(file_index, 7 - rank_index) # Grid position assuming White at bottom
            # Adjust grid position based on flip state.
            blit_grid_pos = (Pt(7, 7) - square_grid_pos) if self.flipped else square_grid_pos
            # Calculate the pixel coordinates for blitting the highlight surface.
            # Multiply the grid position by the symbol size and add the border offset.
            blit_pos = tuple( self._symbol_size * blit_grid_pos + self._border + self.board_origin )
            # Blit the highlight surface onto the screen at the calculated position.
            screen.blit(self._highlight, blit_pos)

        # 3. Draw the pieces.
        # Get the string representation of the board (e.g., "rnbqkbnr\npppppppp\n...").
        board_string = str(self.board)
        # Initialize position tracker for iterating through the board string.
        pos = Pt(0, 0) # Starts at top-left of the internal grid (0,0 corresponds to A8/H1 depending on flip)

        # Iterate through the characters in the board string.
        for c in board_string:
            if c == '\n':
                # If newline, move to the next row and reset the column.
                pos.y += 1
                pos.x = 0
            elif c in self._symbol:
                # If the character is a piece symbol (e.g., 'r', 'P').
                # Determine the grid position for blitting, adjusting for flip state.
                blit_grid_pos = (Pt(7, 7) - pos) if self.flipped else pos
                
                # Calculate the pixel coordinates for blitting the piece image.
                blit_pos = tuple( ( self._symbol_size.x * blit_grid_pos ) + ( self._border + self.board_origin ) )
                
                # Blit the corresponding piece image onto the screen.
                screen.blit(self._symbol[c], blit_pos)
                # Move to the next column in the internal grid.
                pos.x += 1
            elif c == '.':
                # If the character is '.', it's an empty square.
                # Just move to the next column in the internal grid; no piece to draw.
                pos.x += 1

    def size(self):
        """
        Returns the total size of the rendered board image in pixels.
        This includes the board itself and the borders.

        Returns:
            tuple: A tuple (width, height) in pixels.
        """
        # Return the size of the empty board surface, which represents the full board image size.
        return self._empty_board.get_size()

    def select(self, cursor_pos):
        """
        Determines which chess square was clicked based on the mouse cursor position.

        Args:
            cursor_pos (tuple): The (x, y) pixel coordinates of the mouse cursor.

        Returns:
            int or None: The chess.square integer index (0-63) if a square was clicked,
                         None otherwise (if the click was outside the board area).
        """
        # Convert cursor pixel position to a Pt object.
        cursor_pt = Pt(*cursor_pos)
        # Subtract the border offset to get position relative to the inner board area.
        relative_pos = cursor_pt - self._border
        # Divide the relative position by the size of a single square (_symbol_size)
        # to get the grid coordinates (0-7, 0-7) relative to the inner board area's top-left.
        grid_pos = relative_pos // self._symbol_size

        # Check if the calculated grid coordinates are within the 8x8 board range.
        if 0 <= grid_pos.x < 8 and 0 <= grid_pos.y < 8:
            # If within bounds, convert the grid position to a chess.square index (0-63).
            # The grid_pos.x is the file index (0=left, 7=right).
            # The grid_pos.y is the row index (0=top, 7=bottom) relative to the inner board rendering.
            # chess.square() expects file (0=a to 7=h) and rank (0=1 to 7=8).
            # The mapping depends on the flip state.
            if self.flipped:
                # If flipped, grid_pos (0,0) corresponds to H1, (7,7) to A8.
                # File is 7-grid_pos.x, Rank is grid_pos.y.
                return chess.square(7 - grid_pos.x, grid_pos.y)
            else:
                # If not flipped, grid_pos (0,0) corresponds to A8, (7,7) to H1.
                # File is grid_pos.x, Rank is 7-grid_pos.y.
                return chess.square(grid_pos.x, 7 - grid_pos.y)
        else:
            # If the click was outside the 8x8 grid area, return None.
            return None

    def highlight(self, squares):
        """
        Sets the list of squares to be highlighted on the next draw call.

        Args:
            squares (list): A list of chess.square integer indices to highlight.
                            Set to [] to clear all highlights.
        """
        self._highlighted = squares

# Example usage sketch (not part of the module itself):
# pygame.init()
# screen = pygame.display.set_mode((800, 600))
# board = Board(piece_size=80)
# board.draw(screen)
# pygame.display.flip()
# # In main loop: handle events, potentially call board.push(), board.highlight(), board.draw()
# pygame.quit()
